import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/shared/Navbar';
import { satoshi } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className={satoshi.variable}>
      <body className='font-satoshi'>
        <Navbar />
        <main className='min-h-screen p-4 bg-light-yellow md:p-10'>
          {children}
        </main>
      </body>
    </html>
  );
}
