import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/shared/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Navbar />
        <main className='min-h-screen bg-light-yellow md:p-10'>{children}</main>
      </body>
    </html>
  );
}
